<?xml version="1.0" encoding="utf-8"?><Database Name="CarDatabase" Class="VehicleRegistrationDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-LT9U687;Initial Catalog=CarDatabase;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="Car_Project.Repository.Properties.Settings" SettingsPropertyName="CarDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Vehicle" Member="Vehicles">
    <Type Name="Vehicle">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RegistrationNumber" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="NChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="VehicleType" Type="System.String" DbType="NChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="FirstTimeInTraffic" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="YearlyCost" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ServiceHistory" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Service_Vehicle" Member="Service" ThisKey="ServiceHistory" OtherKey="Id" Type="Service" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Service" Member="Services">
    <Type Name="Service">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="IsCompleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Service_Vehicle" Member="Vehicles" ThisKey="Id" OtherKey="ServiceHistory" Type="Vehicle" />
    </Type>
  </Table>
</Database>